name: Auto Update

on: push

jobs:

  check_latest:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: 'x64'
    - name: Check basic libs versions
      run: |
        echo $(python check_version.py pip) > PIP_VERSION
        echo $(python check_version.py poetry) > POETRY_VERSION
        echo $(python -c "from sys import version as v; print('.'.join(v.split(' ')[0].split('.')[:-1]))") > PYTHON_VERSION
        echo $(cat PYTHON_VERSION)-alpine > PYTHON_TAG
        echo "PYTHON_VERSION=$(cat PYTHON_VERSION)"
        echo "PYTHON_TAG=$(cat PYTHON_TAG)"
        echo "PIP_VERSION=$(cat PIP_VERSION)"
        echo "POETRY_VERSION=$(cat POETRY_VERSION)"
    - name: Define meta
      run: |
        echo $(git rev-parse --short HEAD) > VCS_REF
        echo $(date --utc +%FT%TZ) > BUILD_DATE
        echo "$(cat PYTHON_TAG)-$(cat PIP_VERSION)-$(cat POETRY_VERSION)" > BASE_TAG
        echo "VCS_REF=$(cat VCS_REF)"
        echo "BUILD_DATE=$(cat BUILD_DATE)"
        echo "BASE_TAG=$(cat BASE_TAG)"
        
    - name: Build and Push - Base Image
      run: |
        docker build \
          --file docker/poetry.Dockerfile \
          --build-arg PYTHON_TAG=$(cat PYTHON_VERSION)-alpine \
          --build-arg PIP_VERSION=$(cat PIP_VERSION) \
          --build-arg POETRY_VERSION=$(cat POETRY_VERSION) \
          --build-arg VCS_REF=$(cat VCS_REF) \
          --build-arg BUILD_DATE=$(cat BUILD_DATE) \
          --tag pwoolvett/poetry:$(cat BASE_TAG) \
          docker
        docker login \
          --username ${{ secrets.DOCKER_USERNAME }} \
          --password ${{ secrets.DOCKER_PASSWORD }}
        docker push pwoolvett/poetry:$(cat BASE_TAG)
