name: Auto Update

on: push

jobs:

  check_latest:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: 'x64'
    - name: Check basic libs versions
        run: |
          echo $(/home/pwoolvett/Projects/dockers/check_version.py pip) > PIP_VERSION
          echo $(/home/pwoolvett/Projects/dockers/check_version.py poetry) > POETRY_VERSION
          echo "PYTHON_VERSION=$(cat PYTHON_VERSION)"
          echo "PIP_VERSION=$(cat PIP_VERSION)"
          echo "POETRY_VERSION=$(cat POETRY_VERSION)"
