name: Auto Update

on:
  schedule:
    - cron:  '*/1 * * * *'

jobs:

  check_latest:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: 'x64'
    - name: Run a one-line script
        run: |
          git log --format="%H" -n 1 > COMMIT_ID
